# Generated by Django 4.1.7 on 2023-03-21 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seg_permisos',
            fields=[
                ('cod_permisos', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('cod_rol', models.IntegerField()),
                ('per_insercion', models.CharField(default=-1, max_length=1)),
                ('per_eliminar', models.CharField(default=-1, max_length=1)),
                ('per_actualizar', models.CharField(default=-1, max_length=1)),
                ('per_consultar', models.CharField(default=-1, max_length=1)),
                ('fec_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'seg_permisos',
            },
        ),
    ]
